#!/usr/bin/env bash
# Installs Nginx and adds a custom X-Served-By HTTP response header

# Update package lists and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Add the custom header
# We insert it just after the 'server {' line in the default site config
# Using $HOSTNAME explains the SC2154 Shellcheck warning, as this env var is used
sudo sed -i "/server {/a \ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
