#!/usr/bin/env bash
# Install Nginx, ensure it listens on port 80, and restart the service
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart