#!/usr/bin/env bash
# Script that configures a custom 404 page for Nginx

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page
sudo tee /var/www/html/custom_404.html > /dev/null <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>
EOF

# Configure nginx to use custom 404 page
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

# Test configuration and restart nginx
sudo nginx -t && sudo systemctl restart nginx
